//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oneri
    {
        public int ID { get; set; }
        public Nullable<int> YemekID { get; set; }
        public string Tarih { get; set; }
    
        public virtual Yemek Yemek { get; set; }
    }
}
